---
language: python
python:
  - "3.6"
  - "3.7"
matrix:
  include:
  - python: 3.6
    env: TOXENV=black
  - python: 3.6
    env: TOXENV=pylama
install: 
  - pip install tox==3.13.2 tox-travis==0.12
script: 
  - tox
